### PR TITLE
 added missing syscalls to seccomp whitelist 

### PR DESCRIPTION
**Pull request by valoq**
File sometimes reports missing syscalls (when compiling other software)

New syscalls added to whitelist:

getpid
msgget
msgsnd
msgrcv
semget
semop

### CODE REVIEW

**Comment by NieDzejkob** [comment]
This is a mirror. Read the description of the repository if you ever want to get this merged

**Comment by valoq** [comment]
Thank you.
However, all other channels (to the bugtracker and mailing list) are currently down, making this the only way to commit changes.

**Comment by zoulasc** [comment]
Yes, sending mail works and I am trying to get the "regular channels" back up. I am wondering though, what does "compiling other software" mean in this case? Isn't it true that "other software" can always use more syscalls?

**Comment by valoq** [comment]
It just means that during compilation of (general) software file is sometimes used in a way that file reports errors because of blacklisted syscalls. This has nothing to do with the syscalls used by the compiling software.

When investigating the list of syscalls file needs for normal operation, there are still use cases that are not yet covered and therefore some needed syscalls might still be blacklisted. Seems we are getting close to the complete list though.

**Comment by zoulasc** [comment]
How is file used in the compilation of other software? You compile file, you get a binary and then that binary is used how? Where do the extra syscalls come from? Libc?

**Comment by valoq** [comment]
I can't really answer that. All I can say is, that I found error messages in the logs, reporting that file needs additional syscalls to operate normally whenever I compiled a specific software (don't remember what it was). 

There might be some tests that are executed and that use file for some checks.

**Comment by zoulasc** [comment]
Well, while it is easy to click the button to merge, I don't think it is correct to do so without understanding why/when those syscall accesses are happening. After all, the reason we are restricting syscalls is to reduce the attack surface of the program. We should not be adding random ones willy-nilly. Unless you can come up with concrete, reproducible examples why those are required, I am going to close it.

**Comment by valoq** [comment]
You are right, that is a valid point.

I reproduced the error and found several more serious issues.

First, the missing syscalls were reported when using pacman to prepare packages. The errors do not appear when simply compiling code (with or without pacman) but rather during preparation (checking if dependencies exists etc.) and during installation (using file to check if files already exists?)

Secondly I found several more syscalls being reported and they are trouble:

22	pipe
56	clone
59	execve

When using seccomp without a broker architecture, it will only provide protection if the number of syscalls can be kept small and dangerous syscalls are not needed.
However with syscalls like 'execve' on the whitelist, blacklisting any other syscalls is useless.

Assuming the way 'file' is used by pacman is a valid use case, this makes implementing seccomp into 'file' pointless. For seccomp to be a effective sandboxing mechanism for 'file', a broker architecture would be required, meaning quite some work too.

**Comment by zoulasc** [comment]
Well, the pipe/fork(clone)/execve is only when file is trying to decompress files and when those decompressors are not built-in.

**Comment by valoq** [comment]
If the need for those syscalls can be determined beforehand, there might be a way to still blacklist them whenever they are not needed, providing some protection.

Can you tell if that is the case and where this decision would need to be made?

**Comment by zoulasc** [comment]
We can do that, but support to run decompressors is there, but it is only enabled with -z from the command line. I.e. the default options don't need it. The safe use of file is without -z (you should not try to decompress files to find out what they contain if you are trying to be safe).

**Comment by valoq** [comment]
Sounds good.

I will rewrite the filter to skip that use case if -y is used and investigate which syscalls are used under normal circumstances.

**Pull request closed without merging**
