### PR TITLE
add Python 3.8 bytecode

### PR DESCRIPTION
**Pull request by landfillbaby**
considering 3.8 has been stable for a while now and 3.9 has just entered beta, it seems like a good idea

### CODE REVIEW

**Comment by landfillbaby** [comment]
thoughts on including the full list of known versions from [Lib/importlib/_bootstrap_external.py](https://github.com/python/cpython/blob/master/Lib/importlib/_bootstrap_external.py#L167)?

**Comment by landfillbaby** [comment]
oh also I posted this here since all of astron.com seems to be down

**Comment by landfillbaby** [comment]
wait. nevermind

**Comment by landfillbaby** [comment]
oops

**Comment by zoulasc** [comment]
I don't see why not? We should merge the whole list. Do you want to provide a patch for that?

**Comment by landfillbaby** [comment]
ok so is this good? or should i mention which ones are pre-release versions

**Comment by landfillbaby** [comment]
also i have an idea to rework the entire thing to look for the 0x0d0a first, then check and print the leshort at the beginning, and for unknowns, mention the previous and next versions. it might create some kind of conflict with other magic detection though, even more than this already might

**Comment by zoulasc** [comment]
Committed, many thanks!

**Comment by zoulasc** [comment]
We can work on this a bit more, but this is much better than before. Mentioning pre-releases and doing more research is probably not worth it. Changing to look for 0x0d0a first adds complexity, and it seems to me that what we have now is easily understood and grep'able. If you come up with something better we can reconsider.

**Pull request closed without merging**
