### PR TITLE
Add USD file formats

### PR DESCRIPTION
**Pull request by grische**
For more details see here:
http://graphics.pixar.com/usd/docs/Introduction-to-USD.html

Example files can be found here:
https://github.com/PixarAnimationStudios/USD/tree/v20.05/pxr/usd/usd/testenv/testUsdFileFormats

### CODE REVIEW

**Comment by landfillbaby** [comment]
maybe have it say Pixar USD for clarity imo

**Comment by grische** [comment]
@landfillbaby is this needed? It's an open source file format which is used widely across different companies in this field, not limited to Pixar, but originally created by Pixar. 
To quote from their docs:
```
Concretely, USD is an OpenSource project released under a modified Apache license.
```

**Comment by grische** [comment]
What do you think about expanding "USD" into "Universal Scene Description"?
https://en.m.wikipedia.org/wiki/Universal_Scene_Description

**Comment by landfillbaby** [comment]
seems good 👍

**Comment by landfillbaby** [comment]
wait. we need to go through the [mailing list](https://mailman.astron.com/mailman/listinfo/file). oops lol

**Comment by zoulasc** [comment]
Committed, thanks!

**Pull request closed without merging**
