### PR TITLE
Update and rename README to README.md

### PR DESCRIPTION
**Pull request by tanujdhiman**
Add some comments for making it very easy to understand !!

### CODE REVIEW

**Comment by zoulasc** [comment]
Committed, thanks!

**Comment by tanujdhiman** [comment]
I think you have not merged !!

**Comment by zoulasc** [comment]
Looks right to me: https://github.com/file/file/blob/master/README.md <https://github.com/file/file/blob/master/README.md>
Remember that there is a delay syncing to GitHub from CVS. I should
really finish converting the repository to git...

christos

**Comment by glensc** [comment]
@zoulasc what's there to finish? just stop committing to cvs and use git only :D

**Comment by zoulasc** [comment]
I need to finish the release instructions remove RCSID's, and I am not sure what else... I will do it.

**Comment by tanujdhiman** [comment]
Hey !!
I didn't get your points. 🤔

**Pull request closed without merging**
