### PR TITLE
Update fonts

### PR DESCRIPTION
**Pull request by alexmyczko**
detect vga fonts

### CODE REVIEW

**Comment by zoulasc** [comment]
This is not magic; any file with just nul's will be now recognized as a VGA font if I add this magic?

**Comment by alexmyczko** [comment]
Sueing my tests it worked quite good, but is there a way to check the filesize? Then it would be much more safe for false positives, it should be 2048 (8x8), 4096 (8x16)

**Comment by zoulasc** [comment]
I understand, but there is no good way to test for size (that I can think of)...

**Comment by alexmyczko** [comment]
hm, what about the regex capability of file? can i say 8 nulls + 2048-(2*8) bytes + 8 nulls are a VGA font (8x8), and 16 nulls + 4096-(2*16) bytes + 16 nulls are a VGA font (8x16)?

**Comment by zoulasc** [comment]
I think it is better to put the pattern for one of the characters. Nulls are no magic. If your magic matches a file generated by dd if=/dev/zero of=foo count=1000 then it is no good.

**Comment by zoulasc** [comment]
Since there is no magic signature (nuls are no signature) this can't work.

**Pull request closed without merging**
